name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  full:
    name: Node.js 20 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/core
      - name: Run tests
        run: npm test
        working-directory: packages/core
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/core
      - name: Run unit tests
        run: npm test
        working-directory: packages/core